const mongoose = require("mongoose");
const ProductListSchema = new mongoose.Schema({
  name: { type: String, required: true },
  image: { type: String, required: true, trim: true },
  maincategory: {
    type: String,
    required: true,
  },
  subcategory: {
    type: String,
    required: true,
  },
  occasion: { type: String },
  gender: { type: String },
  productImages: { type: Array },
  grams: { type: Number, required: true, trim: true, default: 0 },
  rate: { type: Number, required: false },
  metalMrp: { type: Number },
  metalSellingPrice: { type: Number },
  metalPurity: { type: Number },
  metalWeight: { type: Number },
  metalDiscount: { type: Number },
  metalFinalValue: { type: Number },
  stoneMrp: { type: Number },
  stoneSellingPrice: { type: Number },
  stoneCount: { type: Number },
  stoneWeight: { type: Number },
  stoneDiscount: { type: Number },
  stoneFinalValue: { type: Number },
  makingCharge: { type: Number },
  makingDiscount: { type: Number },
  makingFinalValue: { type: Number },
  wastageCharge: { type: Number },
  wastageDiscount: { type: Number },
  wastageWeight: { type: Number },
  wastageFinalValue: { type: Number },
  totalValue: { type: Number },
  totalDiscount: { type: Number },
  totalFinalValue: { type: Number },
  gstPercentage: { type: Number },
  gstValue: { type: Number },
  gstDiscount: { type: Number },
  gstFinalValue: { type: Number },
  grandTotalValue: { type: Number },
  grandTotalDiscount: { type: Number },
  grandFinalValue: { type: Number },
  status: { type: String, default: 1 },
  createdAt: { type: Date, default: Date.now },
});

const ProductList = mongoose.model("m8it_productlists", ProductListSchema);
module.exports = ProductList;
